Merge in SPA code. Update readme fixes #41
cyclejs-community/create-cycle-app-flavors pull request #43
Opened 2017-07-31 14:47 UTC by SteveALee

This is tested but I had real problems developing against a local flavor! I've still not resolve all the problems. Thus best to test as soon as is published.

Another issue was my formatting was quite different (no semis, spacing around type :)

2017-08-01 09:07 UTC, jvanbruegge requested changes
I think this new template will be a good addition to the flavor

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/app.tsx
> +    'page1' : p1State;
The apostrophes are not needed

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/app.tsx
> +    const initReducer$ = xs.of(
I would write it as `xs.of<Reducer>(prevState => prevState === undefined ? initialState : prevState)` and make `initialState` a global const variable

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/app.tsx
> +        // TODO remove explicit declaration of sink keys if possible
there is a helper in `cyclejs-util`
```ts
const pageSinks = extractSinks(pageSinks$, driverNames);
return {
    ...pageSinks,
    onion: xs.merge(initReducer$, pageSinks.onion)
};
```

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +//import storageDriver from '@cycle/storage'
until the PR is done, you can add the line `declare module '@cycle/storage'` to the `customTypings.d.ts`

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +export function Page1(sources : Sources): Sinks {
I would call it something like CounterComponent

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +    const init$ = xs.of(
Again, would write this as
```ts
xs.of<Reducer>(prevState => prevState === undefined ? { count: 30 } : prevState)
```

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +        speech: touchSpeech$,
I would remove the speech stuff from this component

2017-08-01 09:07 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/pages/page2.tsx
> +export function Page2(sources : Sources): Sinks {
I would call this SpeechComponent, and don't make it a counter, but a text area with a "speak!" button. So the state would be the string

2017-08-01 09:43 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/app.tsx
> +    'page1' : p1State;
ah - hangover from when was keyed by the route which was all sorts of chars.

2017-08-01 09:44 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/app.tsx
> +    const initReducer$ = xs.of(
Agree, I'm working through my project pulling out constants like this :)

2017-08-01 09:45 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/app.tsx
> +        // TODO remove explicit declaration of sink keys if possible
fantastic! Was trying to figure out how best to do it.

2017-08-01 09:46 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +//import storageDriver from '@cycle/storage'
aha - I was wondering about that a I recalled yo usaid it was injected into each page. Thought don't .d.ts pages have special format / contents? Will look at that. Thanks

2017-08-01 09:47 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
driverNames is needed, e.g. for `extractSinks`
```ts
export const driverNames : string[] = Object.keys(mkDrivers()).concat(['onion'])
```

2017-08-01 09:49 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +export function Page1(sources : Sources): Sinks {
I was being laxzy and originally had 2 identical pages. Ispent so long trying to build and test locally tha tI ran out out steam. But you are quite right, better they are different. Thanks for the prod :)

I decidedto call them pages and put in own folder, even though they *are* components. If only as their use is a little different and so use may be specific. I also had a components folder but as was empty git ignored it . Do you think that is a worthless distinction then?

2017-08-01 09:49 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +        speech: touchSpeech$,
:+1:

2017-08-01 09:50 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +    const init$ = xs.of(
:+1:

2017-08-01 09:50 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/pages/page2.tsx
> +export function Page2(sources : Sources): Sinks {
:+1:

2017-08-01 09:51 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/pages/page1.tsx
> +export function Page1(sources : Sources): Sinks {
I don't think a distinction between page and component makes sense.

2017-08-01 09:51 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
hmm, I don't think I ment to remove that.

2017-08-01 09:51 UTC, SteveALee commented
Thanks for a fantastic review. All round was a grreat learning experience for me :)

Will attempt to update tomorrow.

Cheers

2017-08-01 13:38 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
Oh I realise now, I was concerned that calling `driverFn()` an extra time might have undesirable side effects. What do you think?

2017-08-01 13:41 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
Thats not an issue, without `run` a driver is just a function from sinks to sourced
If you call that function with a sink, then you may have side effects. But not before

2017-08-01 13:44 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/pages/page2.tsx
> +export function Page2(sources : Sources): Sinks {
The only advantage of it having a counter is that the separate satet for each was crystal clear. Still with only one counter the state is persisted between page switches

2017-08-01 13:46 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/pages/page2.tsx
> +export function Page2(sources : Sources): Sinks {
I think it's better to show state persistance with two completely distinct components

2017-08-01 13:50 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
But we don't know what a drivers factory function might do as a side effect. As far as I can tell when the driver func is call the driver factories run to create the drivers.

2017-08-01 14:14 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
Yes, that is possible, but unlikely. Anyway I have a better idea:
```ts
const driverThunks = {
    DOM: () => makeDOMDriver('#app'),
    HTTP: () => makeHTTPDriver(),
    Time: () => timeDriver,
    router: () => makeRouterDriver(
        createBrowserHistory(),
        switchPath as RouteMatcher
    ),
    storage: () => storageDriver,
    speech: () => speechDriver
};
const driverNames = Object.keys(driverThunks).concat(['onion']);

const mapReducePairs = fn => Object.keys(driverThunks)
    .map(k => [k, driverThunks[k] ])
    .map(fn)
    .map((k, v) => ({ [k]: v }))
    .reduce(Object.assign, {});

/// #idef PRODUCTION
run(main, mapReducePairs(([k, v]) => [k, v()]))
/// #else
const mkDrivers = () => mapReducePairs(([k, v]) => {
    if(k === 'DOM') { return [k, restartable(v(), { pauseSinksWhileReplaying: false })]; }
    if(k === 'Time') { return [k, v()]; }
    return [k, restartable(v())];
});
const rerun = rerunner(setup, mkDrivers, isolate);
```
I would keep all `ifdef` stuff in one file (the index file)

2017-08-01 16:39 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
Agree that better but need some of that stuff in other files. Ill fix this next

2017-08-01 16:40 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
hmm, Thought I repleied to this. Yes, will fix.

2017-08-01 16:41 UTC, SteveALee commented
I've covered all except the the conditional stuff.

2017-08-01 16:42 UTC, jvanbruegge reviewed
:+1:

2017-08-01 16:42 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/counter.tsx
> +        speech: xs.never(),
This line is not needed

2017-08-01 16:42 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +export interface State {};
I would save the string from the textArea as state

2017-08-01 16:42 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    const init$ = xs.of<Reducer>(
I would just `return xs.of<...`

2017-08-01 16:42 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.mapTo(
I would add a textArea with a custom string here

2017-08-01 16:43 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    const init$ = xs.of<Reducer>(
Well if the textArea string is saved, then the merge will stay

2017-08-01 16:50 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.mapTo(
And as a general note, if your view does not need the state, you normally would just use `xs.of`. Better performance and clearer semantics

2017-08-01 16:51 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/components/counter.tsx
> +        speech: xs.never(),
Ah that was before the extractSinks. 
By the way I see that now returns ALL sinks even ones like time which are source only

2017-08-01 16:52 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +export interface State {};
Why it never changes? Just to make it non empty?

2017-08-01 16:53 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.mapTo(
Ah a new text area - I was confused. Nice idea

2017-08-01 16:54 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/counter.tsx
> +        speech: xs.never(),
that is because we just use the driverNames as keys, even if they wont accept a stream.
Not that bad, because the driver will not care

2017-08-01 16:54 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +export interface State {};
I changes as soon you type?

2017-08-01 16:55 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.mapTo(
Yeah, I meant a `<textarea />` html element

2017-08-01 16:56 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/components/counter.tsx
> +        speech: xs.never(),
yeah - I only spotted as I was previously not returning them. I decided is OK

2017-08-01 16:57 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.mapTo(
I just need to ensure state is kept in sysnc correctly with changes and DOM refreshes. I recall some ways don;t work.

2017-08-01 16:59 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.mapTo(
basicly: state + initialState (important) => textArea value prop => `change` event => reducer (`() => ev.target.value`)

2017-08-01 18:40 UTC, SteveALee commented
Text Area Added - very nice thanks!

So I thought the speak button could speak the textarea content. But how do we get at it without a pull? Some sort of  mapping from the onion stream? Assuming it is remembered? This must be a common requirement

2017-08-01 21:31 UTC, jvanbruegge commented
For the speech component I would use action objects.
```ts
interface SpeechAction { type : 'speech' };
interface UpdateTextAction { type : 'update', reducer : Reducer };
type Action = SpeechAction | UpdateTextAction;
```
Then you can filter + map the Update actions to onionify and filter + sampleCombine(state$) + map to speech driver

2017-08-02 07:06 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/tsconfig.json
> -        "module": "ES6",
I would leave this file unchanged, `es2015` e.g. is not a valid value (`ES2015` would be)

2017-08-02 07:56 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/tsconfig.json
> -        "module": "ES6",
I changed as Code was complaining - it seems it's intellisense is a bit muddled wrt to case, even though it uses the typings

2017-08-02 07:58 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/tsconfig.json
> -        "module": "ES6",
Weird. [This](https://www.typescriptlang.org/docs/handbook/compiler-options.html) lists all possible values, and they are all upper case

2017-08-02 07:59 UTC, SteveALee commented
> That text is not coming from anywhere

Works for me in my project - perhaps a cut n paste error. 
I REALLY need to get local flavors working so I can test it! How do you do it?

2017-08-02 08:03 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/tsconfig.json
> -        "module": "ES6",
YEs, I was just looking at tha tand agree should follow the docs! will revert. Not I think the ES5 is redundant, Did you include it for a reason?

2017-08-02 08:04 UTC, jvanbruegge commented
Since npm 5, it's a pain to develop. The symlinking does not work properly, but I had not yet the time to search for a solution.
So I have a local install of the current flavor and basicly copy + paste my flavor code into `node_modules`

2017-08-02 08:05 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/tsconfig.json
> -        "module": "ES6",
I raised this for the config intellisense https://github.com/Microsoft/vscode/issues/25416

2017-08-02 08:05 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/tsconfig.json
> -        "module": "ES6",
DOM and ES5 are technicly redundant, but it does not hurt to have them

2017-08-02 08:07 UTC, SteveALee commented
Yeah. I think this is the cause but I have no easy solution. #42

2017-08-02 13:03 UTC, jvanbruegge requested changes
:+1:

2017-08-02 13:03 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/counter.tsx
> +    return state$.map({count} =>
you need parenthesis around the argument for destructuring

2017-08-02 13:03 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/components/speaker.tsx
> +    return state$.map({text} =>
Same here

2017-08-02 13:03 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +        'auth0',
Why this auth driver?

2017-08-02 13:03 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +        .reduce((a, c) => Object.assign(a, c), {});
function is redundant, semanticly equivalent with `reduce(Object.assign, {})`

2017-08-02 13:46 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +        .reduce((a, c) => Object.assign(a, c), {});
nope. The callback gets 4 parameters which end up causing extra members. Took me a while to figure that.

2017-08-02 13:47 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/components/counter.tsx
> +    return state$.map({count} =>
Thanks - hand editing after copy :( Bad boy!

2017-08-02 13:48 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +        'auth0',
Because....
Seleted but not pushed yet

2017-08-02 13:55 UTC, SteveALee commented
Shouldn't App.tsx be in components folder now :)

2017-08-02 15:23 UTC, jvanbruegge commented on packages/cycle-scripts-one-fits-all/template/src/drivers.ts
> +        .reduce((a, c) => Object.assign(a, c), {});
Oh, yeah, forgot

2017-08-02 16:08 UTC, SteveALee commented
I think that is it!
I knocked the types into reasonable shape - but note I used the latest typescript so I hope no problems before you can sort out typescript version in the app.

Thanks for all your feedback

2017-08-02 16:09 UTC, SteveALee commented
I'll merge once you clear the changes

2017-08-02 18:03 UTC, SteveALee commented on packages/cycle-scripts-one-fits-all/template/src/index.ts
> -export const driverNames : string[] = Object.keys(drivers || driverFn());
Done

2017-08-03 08:08 UTC, jvanbruegge approved these changes

2017-08-03 08:09 UTC, jvanbruegge commented
I edited quite a lot, I have to test it now and then this can be merged

2017-08-03 08:17 UTC, merged

2017-08-03 08:19 UTC, SteveALee commented
Ooops, I saw I it was approved assumed was tested. Sorry.

Steve Lee
OpenDirective http://opendirective.com

On 3 August 2017 at 09:09, Jan van Brügge <notifications@github.com> wrote:

> I edited quite a lot, I have to test it now and then this can be merged
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyclejs-community/create-cycle-app-flavors/pull/43#issuecomment-319899598>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAlxqgIjslNEbIOI9Jja-zXA33yZTfMQks5sUYApgaJpZM4Oofox>
> .
>

2017-08-03 08:20 UTC, SteveALee commented
At least people use the published version

2017-08-03 08:20 UTC, jvanbruegge commented
Yeah, I will test before releasing it

2017-08-03 08:50 UTC, SteveALee commented
I had a thought about performance as every key press in the text area updates the local storage. I doubt a problem though - unless they have memory leaks. Still you need to worry about mobile battery use sometimes. :) You'd need to synch to back end much less often

2017-08-03 08:52 UTC, jvanbruegge commented
I wanted to do a PR to `storagify` that allows to specify a custom debounce time